# Generated by Django 4.1 on 2023-07-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_profileinfor"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileinfor",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
