# Generated by Django 4.1 on 2023-07-04 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0005_profileinfor_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="vlog",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="vlog_like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
