# Generated by Django 4.1 on 2023-07-05 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_alter_comment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="vlog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commented",
                to="polls.vlog",
            ),
        ),
    ]
