# Generated by Django 4.1 on 2023-07-07 11:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_alter_comment_vlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vlog",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
