# Generated by Django 4.1 on 2023-07-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0010_alter_vlog_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="feedBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField(max_length=500)),
            ],
        ),
    ]
